version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Blue3570!!
      MYSQL_DATABASE: miracleplan
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - miracleplan:/var/lib/mysql

  fastapi:
    image: miracleplan
    container_name: fastapi-container
    restart: always
    environment:
      DATABASE_URL: mysql+mysqlconnector://root:Blue3570!!@mysql:3306/miracleplan
    ports:
      - "8000:8000"
    depends_on:
      - mysql
volumes:
    miracleplan:
