name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: access to secrets
        run: |
          echo "USERNAME=$USERNAME" >> .env
          echo "PASSWORD=$PASSWORD" >> .env
          echo "DOCKER_USERNAME=$DOCKER_USERNAME" >> .env
          echo "DOCKER_PASSWORD=$DOCKER_PASSWORD" >> .env

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t paul3083/miracleplan:latest .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push paul3083/miracleplan:latest

      - name: Deploy to server
        run: |
          docker run -d -p 80:80 paul3083/miracleplan:latest
